#pagemaingame.kv
<PageMainGame>:
    BoxGrey2:
        padding: 1
        BoxBlack:
            padding: 2
            BoxGrey2:
                orientation: 'vertical'
                padding: 10
# Start Titlebox
                BoxTitle:
                    id: box_tit_maingame
# Start Middlebox                
                BoxBlack:
# Start Bottombox                
                BoxBottom:
                    id: box_bot_maingame
